[REVIEW] Add Optuna Demo notebook
rapidsai/cloud-ml-examples pull request #24
Opened 2020-07-07 01:06 UTC by Nanthini10

Adding comparison of Optuna + Dask, bare Optuna, and Sequential Calls.

2020-10-07 19:07 UTC, JohnZed requested changes
Getting really close! Just some wording changes, plus probably removing the last cell (joblib version). Thanks for getting this almost ready to ship now..

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "    max_depth = trial.suggest_int(\"max_depth\", 7, 15)\n",
Maybe add a comment here to explain that we are specifying the search ranges of our params?

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "Optuna uses [study](https://optuna.readthedocs.io/en/stable/reference/study.html) and [trials](https://optuna.readthedocs.io/en/stable/reference/trial.html) to keep track of the HPO experiments.
I'm always hesitant to use the word "optimal" since it's not provably optimal... maybe "best observed trial"

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "Let's look at the importance of the parameter to the performance of the model. This illustrates the impact that the hyperparameters have on the accuracy. We can see that max_depth was more usefu
"importance of each parameter"?

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "Let's look at the importance of the parameter to the performance of the model. This illustrates the impact that the hyperparameters have on the accuracy. We can see that max_depth was more usefu
s/parmters/parameters/

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "This is a slice plot, that observes the actual change of the objective function as the parameters are changes, we see that for higher values of max_depth the acurracy increases."
The visualizations look good!

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "We start a local cluster and keep it ready for running distributed tasks with dask.\n",
Maybe note that if you're running the Dask scheduler on a cluster, this will take advantage of multiple nodes automatically?

2020-10-07 19:07 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAArwAAAH0CAYAAADfWf7fAAAgAElEQVR4XuydBXhURxeGv7gLgSR4gOCuxYtTnOIULQVaoLjT4k6x4tLiDi0ULcXdirtDsCBRSLLx/M+Z9O6/WXY3Kzdks5z7PP/zl+yduTPvzOR+OfvNGaukpKQk8MUEmAA
Not sure this cell is really necessary. We don't articulate why one might prefer this over dask-optuna, and adding a second path seems potentially confusing.

2020-10-07 22:05 UTC, Nanthini10 commented on optuna/notebooks/optuna_rapids.ipynb
> +    "storage_name = \"sqlite:///sample_store.db\""
This is to run the dashboard at the end of the notebook, the dashboard has some visuals and summarizes the experiment.

2020-10-12 20:36 UTC, JohnZed requested changes
Just tiny suggestions. I can go ahead and commit them too.

2020-10-12 20:36 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
> +    "We start a local cluster and keep it ready for running distributed tasks with dask. The dask scheduler can help leverage multiple nodes available on the cluster.\n",
```suggestion
    "We start a local cluster and keep it ready for running multiple workers on the current node.\n",
```
The current location of the multinode thing seems a little confusingly close to the LocalCudaCluster usage.

Then maybe change "Learn more: " in the next paragraph to say something like "Dask can also be used to run a cluster across multiple nodes, leveraging Kubernetes, YARN, or just a manual cluster setup. You can learn more : " (include link)

2020-10-12 20:36 UTC, JohnZed commented on optuna/notebooks/optuna_rapids.ipynb
>      "[LocalCUDACluster](https://github.com/rapidsai/dask-cuda) launches one Dask worker for each GPU in the current systems. It's developed as a part of the RAPIDS project. Learn More:\n",
```suggestion
    "[LocalCUDACluster](https://github.com/rapidsai/dask-cuda) launches one Dask worker for each GPU in the current systems. Dask can also leverage multiple nodes, orchestrating them through a cloud provider, Kubernetes, YARN, or a manual cluster setup. Learn more about Dask setup options here:\n",
```

2020-10-12 20:45 UTC, merged