[WIP] DASK GKE cuML Performance Notebook
rapidsai/cloud-ml-examples pull request #65
Opened 2021-02-09 18:45 UTC by drobison00

2021-02-17 16:21 UTC, zronaghi commented
I'd suggest splitting the notebook into two: 1) Setting up Dask-K8s on GKE and end-to-end workflow (NYC Taxi) with one of the cuML models 2) additional data, algorithms and benchmark scripts.

2021-02-18 22:07 UTC, drobison00 commented
@zronaghi - done. Think this addresses all the issues we've discussed. Just need to wait for 0.18 release to retest the workflows.

2021-03-01 20:04 UTC, drobison00 commented
@zronaghi Workflow is good with the latest 0.18 release. I'm able to follow the blog examples without any deviations. Its ready for public consumption and can be merged on approval.

2021-03-01 22:31 UTC, zronaghi commented
@drobison00 could you also update the README with these notebooks (GCP and Dask)

2021-03-06 01:18 UTC, Nanthini10 requested changes
Looks good to me! I was able to run it fully. I had a few issues with the set-up.

I have a question - why is the `worker_counts` object a list instead of a number?

2021-03-06 02:00 UTC, drobison00 commented on dask/kubernetes/specs/sched-spec.yaml
> +    - image: gcr.io/nv-ai-infra/drobison/dask-unified:0.18
Good catch. I need to update that.

2021-03-06 02:01 UTC, drobison00 commented on dask/kubernetes/specs/worker-spec.yaml
> +          memory: 13G
I'll update this, kind of surprising, the node comes with 16 GB, and usually only consumes .75 with the rest available for allocation.

2021-03-06 02:01 UTC, drobison00 commented
> Looks good to me! I was able to run it fully. There was one memory issue with the set-up YAML file.
> 
> I have a question - why is the `worker_counts` object a list instead of a number?

Worker_counts provides a list of worker counts to sweep, in this case, 8, 4, and 2 workers, which is what the blog uses for the weak scaling runs.

2021-03-08 17:28 UTC, Nanthini10 commented on dask/kubernetes/specs/worker-spec.yaml
> +          memory: 13G
Yeah, that's true. I'm not sure why that happens but on the UI it says just 12.97GB is available for use.

2021-03-08 19:37 UTC, Nanthini10 approved these changes
Looks good to me!

2021-03-15 15:22 UTC, zronaghi approved these changes

2021-03-15 15:23 UTC, merged