[WIP] Updates for XGBoost / FIL examples
rapidsai/cloud-ml-examples pull request #99
Opened 2021-04-23 19:36 UTC by drobison00

Updates required to support additional workflows, custom mortgage data, and FIL inference.

2021-05-03 14:39 UTC, zronaghi requested changes

2021-05-03 14:39 UTC, zronaghi commented on dask/kubernetes/specs/worker-spec-custom.yaml
> +    - image: gcr.io/[YOUR_GCP_PROJECT]/[YOUR_USER_ID]/dask-unified:0.18
Can we update the containers to 0.19? And the Dockerfile in this folder

2021-05-11 18:20 UTC, Nanthini10 approved these changes
Looks good to me, I just have one suggestion

2021-05-11 18:26 UTC, drobison00 commented on dask/kubernetes/specs/sched-spec.yaml
> +          cpu: "10"
That's a good point. I think these moved around a bit while I was testing on different platforms. I'll go back and set them up so they're targeted at n1-standard-4 machines.

2021-05-12 20:27 UTC, zronaghi commented
Looks good, will merge once the default hardware gets updated

2021-05-24 20:33 UTC, zronaghi approved these changes
I'm going to merge this and @Nanthini10 will modify the default params (thanks!)

2021-05-24 20:33 UTC, merged